# Generated by Django 5.2.5 on 2025-10-01 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fondiart_api', '0002_user_bio_user_dni_user_phone_alter_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaComitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_comitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra de Tokens'), ('VENTA', 'Venta de Tokens'), ('DEPOSITO', 'Depósito de Pesos'), ('RETIRO', 'Retiro de Pesos')], max_length=10)),
                ('cantidad_tokens', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('monto_pesos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=10)),
                ('artwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fondiart_api.artwork')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finance.cuentacomitente')),
            ],
        ),
    ]
