# Generated by Django 5.2.5 on 2025-10-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_tokenholding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra de Tokens'), ('VENTA', 'Venta de Tokens'), ('DEPOSITO', 'Depósito de Pesos'), ('RETIRO', 'Retiro de Pesos'), ('DONACION_ENVIADA', 'Donación Enviada'), ('DONACION_RECIBIDA', 'Donación Recibida')], max_length=20),
        ),
    ]
