# Generated by Django 5.2.5 on 2025-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra de Tokens'), ('VENTA', 'Venta de Tokens'), ('DEPOSITO', 'Depósito de Pesos'), ('RETIRO', 'Retiro de Pesos'), ('DONACION_ENVIADA', 'Donación Enviada'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('FINANCIACION_PROYECTO', 'Financiación de Proyecto')], max_length=25),
        ),
    ]
