# Generated by Django 5.2.5 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra de Tokens'), ('VENTA', 'Venta de Tokens'), ('DEPOSITO', 'Depósito de Pesos'), ('RETIRO', 'Retiro de Pesos'), ('DONACION_ENVIADA', 'Donación Enviada'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('FINANCIACION_PROYECTO', 'Financiación de Proyecto'), ('FINANCIACION_RECIBIDA', 'Financiación Recibida')], max_length=25),
        ),
    ]
