# Generated by Django 5.2.5 on 2025-10-28 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_sellorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellorder',
            name='status',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=10),
        ),
    ]
