# Generated by Django 5.2.5 on 2025-10-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0002_user_bio_user_dni_user_phone_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cbu',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
