# Generated by Django 5.2.5 on 2025-10-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0003_user_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='gallery',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/'),
        ),
    ]
