# Generated by Django 5.2.5 on 2025-10-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0004_alter_artwork_gallery_alter_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='estado_venta',
            field=models.CharField(choices=[('publicada', 'Publicada'), ('vendida', 'Vendida'), ('suspendida', 'Suspendida')], default='publicada', max_length=10),
        ),
        migrations.AddField(
            model_name='artwork',
            name='venta_directa',
            field=models.BooleanField(default=False),
        ),
    ]
