# Generated by Django 5.2.5 on 2025-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0006_auction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='fractionFrom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='fractionsLeft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='fractionsTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
