# Generated by Django 5.2.5 on 2025-10-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0007_alter_artwork_fractionfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='contract_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
