# Generated by Django 5.2.5 on 2025-10-04 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0008_artwork_contract_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('amount_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
