# Generated by Django 5.2.5 on 2025-10-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0009_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
