# Generated by Django 5.2.5 on 2025-10-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0010_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funds_disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
