# Generated by Django 5.2.5 on 2025-10-21 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0011_project_funds_disbursed_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='end_date',
            new_name='auction_date',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='start_date',
        ),
    ]
