# Generated by Django 5.2.5 on 2025-10-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0012_rename_end_date_auction_auction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
