# Generated by Django 5.2.5 on 2025-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0013_alter_artwork_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='estado_venta',
            field=models.CharField(choices=[('publicada', 'Publicada'), ('vendida', 'Vendida'), ('suspendida', 'Suspendida'), ('subastada', 'Subastada')], default='publicada', max_length=10),
        ),
    ]
