# Generated by Django 5.2.5 on 2025-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0014_alter_artwork_estado_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='estado_venta',
            field=models.CharField(choices=[('publicada', 'Publicada'), ('vendida', 'Vendida'), ('suspendida', 'Suspendida')], default='publicada', max_length=10),
        ),
    ]
