# Generated by Django 5.2.5 on 2025-10-28 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0015_alter_artwork_estado_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_sales_volume', models.PositiveIntegerField(default=0)),
                ('total_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('average_sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('number_of_artworks_sold', models.PositiveIntegerField(default=0)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('artist', 'date')},
            },
        ),
    ]
