# Generated by Django 5.2.5 on 2025-10-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0017_alter_auction_auction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auction_date',
            field=models.DateTimeField(),
        ),
    ]
