# Generated by Django 5.2.5 on 2025-10-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondiart_api', '0018_alter_auction_auction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='medidas',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='soporte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
