# Generated by Django 5.2.5 on 2025-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('artist_wallet', models.CharField(max_length=42)),
                ('total_tokens', models.PositiveIntegerField()),
                ('artist_tokens', models.PositiveIntegerField(default=0)),
                ('platform_tokens', models.PositiveIntegerField(default=0)),
                ('investor_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
