# Generated by Django 5.2.5 on 2025-10-03 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
        ('fondiart_api', '0006_auction_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuadroToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=42, unique=True)),
                ('token_name', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(max_length=10)),
                ('total_supply', models.PositiveIntegerField()),
                ('deployment_date', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuadro_token', to='fondiart_api.artwork')),
            ],
        ),
        migrations.DeleteModel(
            name='Cuadro',
        ),
    ]
