# Generated by Django 5.2.5 on 2025-10-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_cuadrotoken_delete_cuadro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadrotoken',
            name='tokens_disponibles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuadrotoken',
            name='tokens_vendidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
