# Generated by Django 5.2.5 on 2025-10-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_cuadrotoken_tokens_disponibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuadrotoken',
            name='tokens_disponibles',
            field=models.PositiveIntegerField(default=30000),
        ),
        migrations.AlterField(
            model_name='cuadrotoken',
            name='tokens_vendidos',
            field=models.PositiveIntegerField(default=70000),
        ),
    ]
