from django.urls import path
from .views import (
    RegisterView,
    LoginView,
    MeView,
    UserUpdateMeView,
    ArtworkListView,
    ArtworkCreateView,
    ArtworkRecommendedView,
    ArtworkDetailUpdateView,
    ArtworkDeleteView,
    ArtworkRatingView,
    ArtworkRateView,
    MyArtworksView,
    ArtworkStatsView,
    AdminArtworkListView,
    AdminArtworkStatusUpdateView,
    OrderCreateView,
    OrderListView,
    OrderDetailView,
    FavoriteCreateView,
    FavoriteDeleteView,
    MyFavoritesView,
    WalletDetailView,
    BankAccountListCreateView,
    BankAccountDetailView,
    UserWalletAddressView,
    ArtistArtworkListView,
    NonDirectSaleArtworkListView,
    ImageUploadView,
    AuctionCreateView,
    ArtworkTokenizeView,
    AuctionListView,
    AuctionDetailView,
)

urlpatterns = [
    path('auth/register/', RegisterView.as_view(), name='auth-register'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/me/', MeView.as_view(), name='auth-me'),
    path('users/<int:user_id>/wallet/', UserWalletAddressView.as_view(), name='user-wallet-address'),
    path('users/<int:user_id>/artworks/', ArtistArtworkListView.as_view(), name='user-artwork-list'),
    path('users/me/', UserUpdateMeView.as_view(), name='user-update-me'),

    path('upload/', ImageUploadView.as_view(), name='image-upload'),

    path('artworks/', ArtworkListView.as_view(), name='artwork-list'),
    path('artworks/non-direct-sale/', NonDirectSaleArtworkListView.as_view(), name='artwork-non-direct-sale-list'),
    path('artworks/create/', ArtworkCreateView.as_view(), name='artwork-create'),
    path('artworks/recommended/', ArtworkRecommendedView.as_view(), name='artwork-recommended'),
    path('artworks/<int:pk>/', ArtworkDetailUpdateView.as_view(), name='artwork-detail-update'),
    path('artworks/<int:pk>/delete/', ArtworkDeleteView.as_view(), name='artwork-delete'),
    path('artworks/<int:pk>/rating/', ArtworkRatingView.as_view(), name='artwork-rating'),
    path('artworks/<int:pk>/rate/', ArtworkRateView.as_view(), name='artwork-rate'),
    path('me/artworks/', MyArtworksView.as_view(), name='my-artworks'),
    path('artworks/<int:pk>/stats/', ArtworkStatsView.as_view(), name='artwork-stats'),
    path('artworks/<int:pk>/auctions/create/', AuctionCreateView.as_view(), name='auction-create'),
    path('artworks/<int:pk>/tokenize/', ArtworkTokenizeView.as_view(), name='artwork-tokenize'),

    path('admin/artworks/', AdminArtworkListView.as_view(), name='admin-artwork-list'),
    path('admin/artworks/<int:pk>/status/', AdminArtworkStatusUpdateView.as_view(), name='admin-artwork-status-update'),

    path('orders/create/', OrderCreateView.as_view(), name='order-create'),
    path('orders/list/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),

    path('artworks/<int:pk>/favorite/create/', FavoriteCreateView.as_view(), name='favorite-create'),
    path('artworks/<int:pk>/favorite/delete/', FavoriteDeleteView.as_view(), name='favorite-delete'),
    path('me/favorites/', MyFavoritesView.as_view(), name='my-favorites'),

    path('wallets/me/', WalletDetailView.as_view(), name='wallet-detail'),
    path('bank-accounts/', BankAccountListCreateView.as_view(), name='bank-account-list-create'),
    path('bank-accounts/<int:pk>/', BankAccountDetailView.as_view(), name='bank-account-detail'),
    path('auctions/', AuctionListView.as_view(), name='auction-list'),
    path('auctions/<int:pk>/', AuctionDetailView.as_view(), name='auction-detail'),
]
